### ISSUE TITLE
Terminal screen no response when execute command 'clear' in ashell bash

### ISSUE THREAD

**Issue by wanghongjuan** [nagineni/zephyrjs-cli#2]
## Description
Terminal screen no response when execute command 'clear' in ashell bash

## Steps to Reproduction
1. Run commands `$ node zephyrjs-cli.js -v 32902 -p 63649 -f test/HelloWorld.js`
2. `acm> clear`

## Actual Result
```
$ node zephyrjs-cli.js -v 32902 -p 63649 -f test/HelloWorld.js
33 bytes read
Zephyr.js DEV MODE Apr 13 2017 02:53:31
'A Shell' bash

Commands list:
    help This help
    eval Evaluate JavaScript in real time
   clear Clear the terminal screen
    load [FILE] Saves the input text into a file
     run [FILE] Runs the JavaScript program in the file
   parse [FILE] Check if the JS syntax is correct
    stop Stops current JavaScript execution
      ls [FILE] List directory contents or file stat
     cat [FILE] Print the file contents of a file
      du [FILE] Estimate file space usage
      rm [FILE] Remove file or directory
      mv [SOURCE] [DEST] Move a file to destination
    test Runs your current test
   error Prints an error using JerryScript
    ping Prints '[PONG]' to check that we are alive
      at OK used by the driver when initializing
     set Sets the input mode for 'load' accept data
        transfer raw
        transfer ihex
     get Get states on the shell
  reboot Reboots the device

acm> clear
```
The terminal screen is not response, but when continue to run command `acm> help`, the screen will clear and only show the help message. 

## Expected Result
This behavior is different in ashell feature, when finished running the command, the screen will be clean.

**Comment by nagineni** [comment]
Fixed in https://github.com/nagineni/zephyrjs-cli/commit/d582a38b4a1da20ccf28b4d1b77061c718dae424

**Comment by qiuzhong** [comment]
Verified with [d582a38](https://github.com/nagineni/zephyrjs-cli/commit/d582a38b4a1da20ccf28b4d1b77061c718dae424), this issue is not reproducible.
