### ISSUE TITLE
ashell hangs when execute command 'error' 

### ISSUE THREAD

**Issue by wanghongjuan** [nagineni/zephyrjs-cli#3]
## Description
ashell hangs when execute command 'error' 

## Steps to Reproduction
1. Run commands `$ node zephyrjs-cli.js -v 32902 -p 63649 -f test/HelloWorld.js`
2. `acm> error`

## Actual Result
```
$ node zephyrjs-cli.js -v 32902 -p 63649 -f test/HelloWorld.js
33 bytes read
Zephyr.js DEV MODE Apr 13 2017 02:53:31
'A Shell' bash

Commands list:
    help This help
    eval Evaluate JavaScript in real time
   clear Clear the terminal screen
    load [FILE] Saves the input text into a file
     run [FILE] Runs the JavaScript program in the file
   parse [FILE] Check if the JS syntax is correct
    stop Stops current JavaScript execution
      ls [FILE] List directory contents or file stat
     cat [FILE] Print the file contents of a file
      du [FILE] Estimate file space usage
      rm [FILE] Remove file or directory
      mv [SOURCE] [DEST] Move a file to destination
    test Runs your current test
   error Prints an error using JerryScript
    ping Prints '[PONG]' to check that we are alive
      at OK used by the driver when initializing
     set Sets the input mode for 'load' accept data
        transfer raw
        transfer ihex
     get Get states on the shell
  reboot Reboots the device

acm> error
error
```
The terminal screen is hang, until press 'Enter' keyboard, the screen will return to 'acm>'

## Expected Result
Prints an error using JerryScript

**Comment by nagineni** [comment]
There seems to be an issue with the ashell 'error' command. Could you please check with the ide and see if it works for you?

**Comment by qiuzhong** [comment]
Checked with the IDE . The <code>error</code> command also leads hanging. I got this output:
```
acm> error
stderr test (0
```
Then the IDE console will not response no matter what key you enter.

**Comment by qiuzhong** [comment]
zephyr.js bug: [#1027](https://github.com/01org/zephyr.js/issues/1027)

**Comment by nagineni** [comment]
`error` command doesn't exit anymore in ashell. Closing this.

**Comment by xiaoyu3x** [comment]
hi, @wanghongjuan 

According to latest [ashell](https://github.com/01org/zephyr.js/blob/master/docs/ashell.md#commands) doc, 'error' cmd has been removed, so closed it please.
